"""Shared labels and presentation priorities for model-backed statistics."""

STAT_LABELS = {
    "goals_p90": ("Goals", "per 90"),
    "xg_p90": ("xG", "per 90"),
    "npxg_p90": ("Non-penalty xG", "per 90"),
    "npxg_per_shot": ("npxG per shot", ""),
    "shots_p90": ("Shots", "per 90"),
    "shots_on_target_p90": ("Shots on target", "per 90"),
    "shot_accuracy_pct": ("Shot accuracy", "%"),
    "assists_p90": ("Assists", "per 90"),
    "xag_p90": ("xAG", "per 90"),
    "xa_p90": ("xA", "per 90"),
    "key_passes_p90": ("Key passes", "per 90"),
    "shot_creating_actions_p90": ("Shot-creating actions", "per 90"),
    "goal_creating_actions_p90": ("Goal-creating actions", "per 90"),
    "passes_completed_p90": ("Passes completed", "per 90"),
    "passes_attempted_p90": ("Passes attempted", "per 90"),
    "progressive_passes_p90": ("Progressive passes", "per 90"),
    "passes_final_third_p90": ("Passes into final third", "per 90"),
    "passes_penalty_area_p90": ("Passes into penalty area", "per 90"),
    "through_balls_p90": ("Through balls", "per 90"),
    "crosses_p90": ("Crosses", "per 90"),
    "crosses_penalty_area_p90": ("Crosses into penalty area", "per 90"),
    "pass_completion_pct": ("Pass completion", "%"),
    "progressive_carries_p90": ("Progressive carries", "per 90"),
    "carries_final_third_p90": ("Carries into final third", "per 90"),
    "carries_penalty_area_p90": ("Carries into penalty area", "per 90"),
    "carries_p90": ("Carries", "per 90"),
    "touches_p90": ("Touches", "per 90"),
    "successful_takeons_p90": ("Successful take-ons", "per 90"),
    "takeons_attempted_p90": ("Take-ons attempted", "per 90"),
    "takeon_success_pct": ("Take-on success", "%"),
    "passes_received_p90": ("Passes received", "per 90"),
    "progressive_receptions_p90": ("Progressive receptions", "per 90"),
    "attacking_penalty_area_touches_p90": ("Touches in penalty area", "per 90"),
    "attacking_third_touches_p90": ("Touches in attacking third", "per 90"),
    "defensive_penalty_area_touches_p90": (
        "Touches in defensive penalty area",
        "per 90",
    ),
    "tackles_p90": ("Tackles", "per 90"),
    "tackles_won_p90": ("Tackles won", "per 90"),
    "interceptions_p90": ("Interceptions", "per 90"),
    "clearances_p90": ("Clearances", "per 90"),
    "blocks_p90": ("Blocks", "per 90"),
    "recoveries_p90": ("Recoveries", "per 90"),
    "errors_p90": ("Errors", "per 90"),
    "aerials_won_p90": ("Aerials won", "per 90"),
    "aerial_win_pct": ("Aerial win rate", "%"),
    "yellow_p90": ("Yellow cards", "per 90"),
    "red_p90": ("Red cards", "per 90"),
    "fouls_p90": ("Fouls", "per 90"),
    "fouls_drawn_p90": ("Fouls drawn", "per 90"),
    "miscontrols_p90": ("Miscontrols", "per 90"),
    "dispossessed_p90": ("Dispossessed", "per 90"),
    "saves_p90": ("Saves", "per 90"),
    "save_pct": ("Save rate", "%"),
    "clean_sheet_pct": ("Clean sheet rate", "%"),
    "psxg_p90": ("Post-shot xG faced", "per 90"),
    "goals_prevented_p90": ("Goals prevented", "per 90"),
    "gk_pass_completion_pct": ("GK pass completion", "%"),
    "gk_passes_attempted_p90": ("GK passes attempted", "per 90"),
    "gk_throws_p90": ("Throws", "per 90"),
    "gk_launch_pct": ("Launched pass rate", "%"),
    "gk_average_pass_length": ("Average pass length", "yards"),
    "crosses_stopped_pct": ("Crosses stopped", "%"),
    "defensive_actions_outside_box_p90": ("Actions outside box", "per 90"),
    "avg_defensive_action_distance": ("Average action distance", "yards"),
}

GOALKEEPER_STAT_KEYS = {
    "saves_p90",
    "save_pct",
    "clean_sheet_pct",
    "psxg_p90",
    "goals_prevented_p90",
    "gk_pass_completion_pct",
    "gk_passes_attempted_p90",
    "gk_throws_p90",
    "gk_launch_pct",
    "gk_average_pass_length",
    "crosses_stopped_pct",
    "defensive_actions_outside_box_p90",
    "avg_defensive_action_distance",
}

FAMILY_STAT_PRIORITIES = {
    "GK": [
        "goals_prevented_p90",
        "save_pct",
        "saves_p90",
        "clean_sheet_pct",
        "defensive_actions_outside_box_p90",
        "gk_pass_completion_pct",
    ],
    "CB": [
        "interceptions_p90",
        "clearances_p90",
        "aerials_won_p90",
        "blocks_p90",
        "tackles_won_p90",
        "progressive_passes_p90",
    ],
    "FB_WB": [
        "tackles_won_p90",
        "interceptions_p90",
        "progressive_carries_p90",
        "progressive_passes_p90",
        "key_passes_p90",
        "crosses_p90",
    ],
    "DM": [
        "interceptions_p90",
        "tackles_won_p90",
        "recoveries_p90",
        "progressive_passes_p90",
        "passes_completed_p90",
        "pass_completion_pct",
    ],
    "CM": [
        "progressive_passes_p90",
        "progressive_carries_p90",
        "passes_completed_p90",
        "key_passes_p90",
        "recoveries_p90",
        "xag_p90",
    ],
    "AM": [
        "xag_p90",
        "xa_p90",
        "key_passes_p90",
        "shot_creating_actions_p90",
        "progressive_carries_p90",
        "goals_p90",
    ],
    "W": [
        "successful_takeons_p90",
        "progressive_carries_p90",
        "xag_p90",
        "key_passes_p90",
        "npxg_p90",
        "carries_penalty_area_p90",
    ],
    "ST": [
        "npxg_p90",
        "xg_p90",
        "goals_p90",
        "shots_on_target_p90",
        "attacking_penalty_area_touches_p90",
        "aerials_won_p90",
    ],
}

FAMILY_COMPARISON_STATS = {
    family: list(
        dict.fromkeys(
            stats
            + [
                "passes_completed_p90",
                "progressive_passes_p90",
                "progressive_carries_p90",
                "tackles_p90",
                "interceptions_p90",
            ]
        )
    )[:11]
    for family, stats in FAMILY_STAT_PRIORITIES.items()
}
